version: '3.7'

services:
  db:
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    environment:
      WAIT_HOSTS: db:5432
    command: >
        sh -c "/wait
        && bin/start"
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web

