version: '3.7'

services:
  db:
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    command: bin/start
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - db

